//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace client_net.ShopServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="createUser", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class createUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string nameFieldField;
        
        private string usernameFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nameField {
            get {
                return this.nameFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.nameFieldField, value) != true)) {
                    this.nameFieldField = value;
                    this.RaisePropertyChanged("nameField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string usernameField {
            get {
                return this.usernameFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameFieldField, value) != true)) {
                    this.usernameFieldField = value;
                    this.RaisePropertyChanged("usernameField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="createUserResponse", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class createUserResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string nameFieldField;
        
        private string passwordFieldField;
        
        private string useridFieldField;
        
        private string usernameFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nameField {
            get {
                return this.nameFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.nameFieldField, value) != true)) {
                    this.nameFieldField = value;
                    this.RaisePropertyChanged("nameField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string passwordField {
            get {
                return this.passwordFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordFieldField, value) != true)) {
                    this.passwordFieldField = value;
                    this.RaisePropertyChanged("passwordField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string useridField {
            get {
                return this.useridFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.useridFieldField, value) != true)) {
                    this.useridFieldField = value;
                    this.RaisePropertyChanged("useridField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string usernameField {
            get {
                return this.usernameFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameFieldField, value) != true)) {
                    this.usernameFieldField = value;
                    this.RaisePropertyChanged("usernameField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="loginUser", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class loginUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string passwordFieldField;
        
        private string usernameFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string passwordField {
            get {
                return this.passwordFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordFieldField, value) != true)) {
                    this.passwordFieldField = value;
                    this.RaisePropertyChanged("passwordField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string usernameField {
            get {
                return this.usernameFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameFieldField, value) != true)) {
                    this.usernameFieldField = value;
                    this.RaisePropertyChanged("usernameField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="loginUserResponse", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class loginUserResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private float balanceFieldField;
        
        private bool successFieldField;
        
        private string useridFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float balanceField {
            get {
                return this.balanceFieldField;
            }
            set {
                if ((this.balanceFieldField.Equals(value) != true)) {
                    this.balanceFieldField = value;
                    this.RaisePropertyChanged("balanceField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool successField {
            get {
                return this.successFieldField;
            }
            set {
                if ((this.successFieldField.Equals(value) != true)) {
                    this.successFieldField = value;
                    this.RaisePropertyChanged("successField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string useridField {
            get {
                return this.useridFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.useridFieldField, value) != true)) {
                    this.useridFieldField = value;
                    this.RaisePropertyChanged("useridField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="userDetails", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class userDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string userFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string userField {
            get {
                return this.userFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.userFieldField, value) != true)) {
                    this.userFieldField = value;
                    this.RaisePropertyChanged("userField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="userDetailsResponse", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class userDetailsResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private float balanceFieldField;
        
        private string nameFieldField;
        
        private string useridFieldField;
        
        private string usernameFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float balanceField {
            get {
                return this.balanceFieldField;
            }
            set {
                if ((this.balanceFieldField.Equals(value) != true)) {
                    this.balanceFieldField = value;
                    this.RaisePropertyChanged("balanceField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nameField {
            get {
                return this.nameFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.nameFieldField, value) != true)) {
                    this.nameFieldField = value;
                    this.RaisePropertyChanged("nameField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string useridField {
            get {
                return this.useridFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.useridFieldField, value) != true)) {
                    this.useridFieldField = value;
                    this.RaisePropertyChanged("useridField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string usernameField {
            get {
                return this.usernameFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameFieldField, value) != true)) {
                    this.usernameFieldField = value;
                    this.RaisePropertyChanged("usernameField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="purchaseProduct", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class purchaseProduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string productFieldField;
        
        private string userFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string productField {
            get {
                return this.productFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.productFieldField, value) != true)) {
                    this.productFieldField = value;
                    this.RaisePropertyChanged("productField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string userField {
            get {
                return this.userFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.userFieldField, value) != true)) {
                    this.userFieldField = value;
                    this.RaisePropertyChanged("userField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="purchaseProductResponse", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class purchaseProductResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private float balanceFieldField;
        
        private bool successFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float balanceField {
            get {
                return this.balanceFieldField;
            }
            set {
                if ((this.balanceFieldField.Equals(value) != true)) {
                    this.balanceFieldField = value;
                    this.RaisePropertyChanged("balanceField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool successField {
            get {
                return this.successFieldField;
            }
            set {
                if ((this.successFieldField.Equals(value) != true)) {
                    this.successFieldField = value;
                    this.RaisePropertyChanged("successField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="productList", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class productList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/server")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private client_net.ShopServiceReference.Purchase[] PurchaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int productidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int quantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public client_net.ShopServiceReference.Purchase[] Purchase {
            get {
                return this.PurchaseField;
            }
            set {
                if ((object.ReferenceEquals(this.PurchaseField, value) != true)) {
                    this.PurchaseField = value;
                    this.RaisePropertyChanged("Purchase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int productid {
            get {
                return this.productidField;
            }
            set {
                if ((this.productidField.Equals(value) != true)) {
                    this.productidField = value;
                    this.RaisePropertyChanged("productid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((this.quantityField.Equals(value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Purchase", Namespace="http://schemas.datacontract.org/2004/07/server")]
    [System.SerializableAttribute()]
    public partial class Purchase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private client_net.ShopServiceReference.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private client_net.ShopServiceReference.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int productidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int purchaseidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int useridField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public client_net.ShopServiceReference.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public client_net.ShopServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int productid {
            get {
                return this.productidField;
            }
            set {
                if ((this.productidField.Equals(value) != true)) {
                    this.productidField = value;
                    this.RaisePropertyChanged("productid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int purchaseid {
            get {
                return this.purchaseidField;
            }
            set {
                if ((this.purchaseidField.Equals(value) != true)) {
                    this.purchaseidField = value;
                    this.RaisePropertyChanged("purchaseid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userid {
            get {
                return this.useridField;
            }
            set {
                if ((this.useridField.Equals(value) != true)) {
                    this.useridField = value;
                    this.RaisePropertyChanged("userid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/server")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private client_net.ShopServiceReference.Purchase[] PurchaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal balanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int useridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public client_net.ShopServiceReference.Purchase[] Purchase {
            get {
                return this.PurchaseField;
            }
            set {
                if ((object.ReferenceEquals(this.PurchaseField, value) != true)) {
                    this.PurchaseField = value;
                    this.RaisePropertyChanged("Purchase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal balance {
            get {
                return this.balanceField;
            }
            set {
                if ((this.balanceField.Equals(value) != true)) {
                    this.balanceField = value;
                    this.RaisePropertyChanged("balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userid {
            get {
                return this.useridField;
            }
            set {
                if ((this.useridField.Equals(value) != true)) {
                    this.useridField = value;
                    this.RaisePropertyChanged("userid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="historyList", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class historyList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string userFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string userField {
            get {
                return this.userFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.userFieldField, value) != true)) {
                    this.userFieldField = value;
                    this.RaisePropertyChanged("userField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ShopServiceReference.IShopService")]
    public interface IShopService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopService/CreateUser", ReplyAction="http://tempuri.org/IShopService/CreateUserResponse")]
        client_net.ShopServiceReference.createUserResponse CreateUser(client_net.ShopServiceReference.createUser data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopService/CreateUser", ReplyAction="http://tempuri.org/IShopService/CreateUserResponse")]
        System.Threading.Tasks.Task<client_net.ShopServiceReference.createUserResponse> CreateUserAsync(client_net.ShopServiceReference.createUser data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopService/LoginUser", ReplyAction="http://tempuri.org/IShopService/LoginUserResponse")]
        client_net.ShopServiceReference.loginUserResponse LoginUser(client_net.ShopServiceReference.loginUser data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopService/LoginUser", ReplyAction="http://tempuri.org/IShopService/LoginUserResponse")]
        System.Threading.Tasks.Task<client_net.ShopServiceReference.loginUserResponse> LoginUserAsync(client_net.ShopServiceReference.loginUser data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopService/UserDetails", ReplyAction="http://tempuri.org/IShopService/UserDetailsResponse")]
        client_net.ShopServiceReference.userDetailsResponse UserDetails(client_net.ShopServiceReference.userDetails data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopService/UserDetails", ReplyAction="http://tempuri.org/IShopService/UserDetailsResponse")]
        System.Threading.Tasks.Task<client_net.ShopServiceReference.userDetailsResponse> UserDetailsAsync(client_net.ShopServiceReference.userDetails data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopService/PurchaseProduct", ReplyAction="http://tempuri.org/IShopService/PurchaseProductResponse")]
        client_net.ShopServiceReference.purchaseProductResponse PurchaseProduct(client_net.ShopServiceReference.purchaseProduct data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopService/PurchaseProduct", ReplyAction="http://tempuri.org/IShopService/PurchaseProductResponse")]
        System.Threading.Tasks.Task<client_net.ShopServiceReference.purchaseProductResponse> PurchaseProductAsync(client_net.ShopServiceReference.purchaseProduct data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopService/ProductList", ReplyAction="http://tempuri.org/IShopService/ProductListResponse")]
        client_net.ShopServiceReference.Product[] ProductList(client_net.ShopServiceReference.productList data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopService/ProductList", ReplyAction="http://tempuri.org/IShopService/ProductListResponse")]
        System.Threading.Tasks.Task<client_net.ShopServiceReference.Product[]> ProductListAsync(client_net.ShopServiceReference.productList data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopService/HistoryList", ReplyAction="http://tempuri.org/IShopService/HistoryListResponse")]
        client_net.ShopServiceReference.Product[] HistoryList(client_net.ShopServiceReference.historyList data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopService/HistoryList", ReplyAction="http://tempuri.org/IShopService/HistoryListResponse")]
        System.Threading.Tasks.Task<client_net.ShopServiceReference.Product[]> HistoryListAsync(client_net.ShopServiceReference.historyList data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShopServiceChannel : client_net.ShopServiceReference.IShopService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShopServiceClient : System.ServiceModel.ClientBase<client_net.ShopServiceReference.IShopService>, client_net.ShopServiceReference.IShopService {
        
        public ShopServiceClient() {
        }
        
        public ShopServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShopServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShopServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShopServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public client_net.ShopServiceReference.createUserResponse CreateUser(client_net.ShopServiceReference.createUser data) {
            return base.Channel.CreateUser(data);
        }
        
        public System.Threading.Tasks.Task<client_net.ShopServiceReference.createUserResponse> CreateUserAsync(client_net.ShopServiceReference.createUser data) {
            return base.Channel.CreateUserAsync(data);
        }
        
        public client_net.ShopServiceReference.loginUserResponse LoginUser(client_net.ShopServiceReference.loginUser data) {
            return base.Channel.LoginUser(data);
        }
        
        public System.Threading.Tasks.Task<client_net.ShopServiceReference.loginUserResponse> LoginUserAsync(client_net.ShopServiceReference.loginUser data) {
            return base.Channel.LoginUserAsync(data);
        }
        
        public client_net.ShopServiceReference.userDetailsResponse UserDetails(client_net.ShopServiceReference.userDetails data) {
            return base.Channel.UserDetails(data);
        }
        
        public System.Threading.Tasks.Task<client_net.ShopServiceReference.userDetailsResponse> UserDetailsAsync(client_net.ShopServiceReference.userDetails data) {
            return base.Channel.UserDetailsAsync(data);
        }
        
        public client_net.ShopServiceReference.purchaseProductResponse PurchaseProduct(client_net.ShopServiceReference.purchaseProduct data) {
            return base.Channel.PurchaseProduct(data);
        }
        
        public System.Threading.Tasks.Task<client_net.ShopServiceReference.purchaseProductResponse> PurchaseProductAsync(client_net.ShopServiceReference.purchaseProduct data) {
            return base.Channel.PurchaseProductAsync(data);
        }
        
        public client_net.ShopServiceReference.Product[] ProductList(client_net.ShopServiceReference.productList data) {
            return base.Channel.ProductList(data);
        }
        
        public System.Threading.Tasks.Task<client_net.ShopServiceReference.Product[]> ProductListAsync(client_net.ShopServiceReference.productList data) {
            return base.Channel.ProductListAsync(data);
        }
        
        public client_net.ShopServiceReference.Product[] HistoryList(client_net.ShopServiceReference.historyList data) {
            return base.Channel.HistoryList(data);
        }
        
        public System.Threading.Tasks.Task<client_net.ShopServiceReference.Product[]> HistoryListAsync(client_net.ShopServiceReference.historyList data) {
            return base.Channel.HistoryListAsync(data);
        }
    }
}
