
package nl.arvici.ahshop.wsinterface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.server.CreateUserData;
import org.datacontract.schemas._2004._07.server.HistoryListData;
import org.datacontract.schemas._2004._07.server.LoginUserData;
import org.datacontract.schemas._2004._07.server.PurchaseProductData;
import org.datacontract.schemas._2004._07.server.ServiceResponseOfArrayOfProductUEsMBek5;
import org.datacontract.schemas._2004._07.server.ServiceResponseOfArrayOfPurchaseUEsMBek5;
import org.datacontract.schemas._2004._07.server.ServiceResponseOfPurchaseUEsMBek5;
import org.datacontract.schemas._2004._07.server.ServiceResponseOfUserUEsMBek5;
import org.datacontract.schemas._2004._07.server.UserDetailsData;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IShopService", targetNamespace = "http://arvici.nl/ahshop/wsinterface")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    nl.arvici.ahshop.wsinterface.ObjectFactory.class,
    org.datacontract.schemas._2004._07.server.ObjectFactory.class
})
public interface IShopService {


    /**
     * 
     * @param data
     * @return
     *     returns org.datacontract.schemas._2004._07.server.ServiceResponseOfUserUEsMBek5
     */
    @WebMethod(operationName = "CreateUser", action = "http://arvici.nl/ahshop/wsinterface/IShopService/CreateUser")
    @WebResult(name = "CreateUserResult", targetNamespace = "http://arvici.nl/ahshop/wsinterface")
    @RequestWrapper(localName = "CreateUser", targetNamespace = "http://arvici.nl/ahshop/wsinterface", className = "nl.arvici.ahshop.wsinterface.CreateUser")
    @ResponseWrapper(localName = "CreateUserResponse", targetNamespace = "http://arvici.nl/ahshop/wsinterface", className = "nl.arvici.ahshop.wsinterface.CreateUserResponse")
    public ServiceResponseOfUserUEsMBek5 createUser(
        @WebParam(name = "data", targetNamespace = "http://arvici.nl/ahshop/wsinterface")
        CreateUserData data);

    /**
     * 
     * @param data
     * @return
     *     returns org.datacontract.schemas._2004._07.server.ServiceResponseOfUserUEsMBek5
     */
    @WebMethod(operationName = "LoginUser", action = "http://arvici.nl/ahshop/wsinterface/IShopService/LoginUser")
    @WebResult(name = "LoginUserResult", targetNamespace = "http://arvici.nl/ahshop/wsinterface")
    @RequestWrapper(localName = "LoginUser", targetNamespace = "http://arvici.nl/ahshop/wsinterface", className = "nl.arvici.ahshop.wsinterface.LoginUser")
    @ResponseWrapper(localName = "LoginUserResponse", targetNamespace = "http://arvici.nl/ahshop/wsinterface", className = "nl.arvici.ahshop.wsinterface.LoginUserResponse")
    public ServiceResponseOfUserUEsMBek5 loginUser(
        @WebParam(name = "data", targetNamespace = "http://arvici.nl/ahshop/wsinterface")
        LoginUserData data);

    /**
     * 
     * @param data
     * @return
     *     returns org.datacontract.schemas._2004._07.server.ServiceResponseOfUserUEsMBek5
     */
    @WebMethod(operationName = "UserDetails", action = "http://arvici.nl/ahshop/wsinterface/IShopService/UserDetails")
    @WebResult(name = "UserDetailsResult", targetNamespace = "http://arvici.nl/ahshop/wsinterface")
    @RequestWrapper(localName = "UserDetails", targetNamespace = "http://arvici.nl/ahshop/wsinterface", className = "nl.arvici.ahshop.wsinterface.UserDetails")
    @ResponseWrapper(localName = "UserDetailsResponse", targetNamespace = "http://arvici.nl/ahshop/wsinterface", className = "nl.arvici.ahshop.wsinterface.UserDetailsResponse")
    public ServiceResponseOfUserUEsMBek5 userDetails(
        @WebParam(name = "data", targetNamespace = "http://arvici.nl/ahshop/wsinterface")
        UserDetailsData data);

    /**
     * 
     * @param data
     * @return
     *     returns org.datacontract.schemas._2004._07.server.ServiceResponseOfPurchaseUEsMBek5
     */
    @WebMethod(operationName = "PurchaseProduct", action = "http://arvici.nl/ahshop/wsinterface/IShopService/PurchaseProduct")
    @WebResult(name = "PurchaseProductResult", targetNamespace = "http://arvici.nl/ahshop/wsinterface")
    @RequestWrapper(localName = "PurchaseProduct", targetNamespace = "http://arvici.nl/ahshop/wsinterface", className = "nl.arvici.ahshop.wsinterface.PurchaseProduct")
    @ResponseWrapper(localName = "PurchaseProductResponse", targetNamespace = "http://arvici.nl/ahshop/wsinterface", className = "nl.arvici.ahshop.wsinterface.PurchaseProductResponse")
    public ServiceResponseOfPurchaseUEsMBek5 purchaseProduct(
        @WebParam(name = "data", targetNamespace = "http://arvici.nl/ahshop/wsinterface")
        PurchaseProductData data);

    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.server.ServiceResponseOfArrayOfProductUEsMBek5
     */
    @WebMethod(operationName = "ProductList", action = "http://arvici.nl/ahshop/wsinterface/IShopService/ProductList")
    @WebResult(name = "ProductListResult", targetNamespace = "http://arvici.nl/ahshop/wsinterface")
    @RequestWrapper(localName = "ProductList", targetNamespace = "http://arvici.nl/ahshop/wsinterface", className = "nl.arvici.ahshop.wsinterface.ProductList")
    @ResponseWrapper(localName = "ProductListResponse", targetNamespace = "http://arvici.nl/ahshop/wsinterface", className = "nl.arvici.ahshop.wsinterface.ProductListResponse")
    public ServiceResponseOfArrayOfProductUEsMBek5 productList();

    /**
     * 
     * @param data
     * @return
     *     returns org.datacontract.schemas._2004._07.server.ServiceResponseOfArrayOfPurchaseUEsMBek5
     */
    @WebMethod(operationName = "HistoryList", action = "http://arvici.nl/ahshop/wsinterface/IShopService/HistoryList")
    @WebResult(name = "HistoryListResult", targetNamespace = "http://arvici.nl/ahshop/wsinterface")
    @RequestWrapper(localName = "HistoryList", targetNamespace = "http://arvici.nl/ahshop/wsinterface", className = "nl.arvici.ahshop.wsinterface.HistoryList")
    @ResponseWrapper(localName = "HistoryListResponse", targetNamespace = "http://arvici.nl/ahshop/wsinterface", className = "nl.arvici.ahshop.wsinterface.HistoryListResponse")
    public ServiceResponseOfArrayOfPurchaseUEsMBek5 historyList(
        @WebParam(name = "data", targetNamespace = "http://arvici.nl/ahshop/wsinterface")
        HistoryListData data);

}
